
# AWS Configuration
AWS_ACCESS_KEY_ID = "XXXXXXX"
AWS_SECRET_ACCESS_KEY = "XXXXXXX"
AWS_REGION = "us-east-1"
S3_BUCKET_NAME = "molecular-property-pipeline"

# Snowflake Configuration
SNOWFLAKE_ACCOUNT = "XXXXXXX"
SNOWFLAKE_USER = "XXXXXXX"
SNOWFLAKE_PASSWORD = "XXXXXXX"
SNOWFLAKE_DATABASE = "MOLECULAR_DB"
SNOWFLAKE_SCHEMA = "PUBLIC"
SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"
